/** Shared `useState` keys. A typo here is a compile error, not a silent second store. */
export const STATE = {
  authUser: 'auth-user',
  authReady: 'auth-ready',
  authDialog: 'auth-dialog',
  authError: 'auth-error',
  authSending: 'auth-sending',
  authVerifying: 'auth-verifying',
  authOtpEmail: 'auth-otp-email',
  authStep: 'auth-step',
  authValuationCount: 'auth-valuation-count',
  authCreditBalance: 'auth-credit-balance',
  authCheckoutNotice: 'auth-checkout-notice',
  authCheckoutBusy: 'auth-checkout-busy',
  authCheckoutError: 'auth-checkout-error',
  toolsTab: 'tools-tab',
  lastLookup: 'last-lookup',
  pendingLookup: 'pending-lookup',
  nnumber: 'nn',
  compsModel: 'c-model',
  clMake: 'cl-make',
  clModel: 'cl-model',
  clYear: 'cl-year',
  clEng: 'cl-eng',
  clClear: 'cl-clear',
  ctxEngModel: 'ctx-eng-model',
  ctxAcType: 'ctx-ac-type',
  ctxNumEng: 'ctx-num-eng',
  ctxValEngMake: 'ctx-val-eng-make',
  ctxValEngModel: 'ctx-val-eng-model',
  engineTboCache: 'engine-tbo-cache',
  lastEngineLife: 'last-engine-life',
  vForm: 'v-form',
  vFormPersistBound: 'v-form-persist-bound',
  vTboNote: 'v-tbo-note',
  vHasResult: 'v-has-result',
  shareOrigin: 'share-origin',
} as const
